"""v0.3 added website name 

Revision ID: 5662f1255cad
Revises: 0cf1d41d3e5c
Create Date: 2023-04-13 15:54:11.883394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5662f1255cad'
down_revision = '0cf1d41d3e5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('name', sa.String(length=1028), nullable=True))
    op.add_column('article', sa.Column('website_url', sa.String(length=1028), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('article', 'website_url')
    op.drop_column('article', 'name')
    # ### end Alembic commands ###
